# ports/web_client_port.py
from typing import Protocol

class WebClientPort(Protocol):
    def open(self, url: str) -> None: ...
    def wait(self, seconds: float) -> None: ...
    def find_and_type(self, by: str, selector: str, text: str, paste: bool=False) -> None: ...
    def click(self, by: str, selector: str) -> None: ...
    def page_source(self) -> str: ...
    def close(self) -> None: ...
